name: flexible_mobile_scanner
description: A fork of mobile_scanner with more flexible options - scanWindowBuilder and cameraPreviewBuilder.
version: 1.0.0
repository: https://github.com/sgaku/flexible_mobile_scanner

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ">=1.10.0 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.steenbakker.mobile_scanner
        pluginClass: MobileScannerPlugin
      ios:
        pluginClass: FlexibleMobileScannerPlugin
      macos:
        pluginClass: FlexibleMobileScannerPlugin
      web:
        pluginClass: MobileScannerWebPlugin
        fileName: mobile_scanner_web_plugin.dart